name: Test
on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: first
        run: |
          echo "I'm running"
